### ISSUE TITLE
Validação ocorrendo em parte do registro

### ISSUE THREAD

**Issue by mozgbrasil** [RodrigoOler/node-cpf-cnpj#1]
Boa Tarde

Ola tudo bem

Estou efetuando um teste

E tenho o seguinte CPF valido

316.328.549-02

Mas ao utilizar sua biblioteca e informar qualquer coisa a partir do ultimo numero, também é retornado como valido

Caso que venha a informar

316.328.549-02x

Retorna true

**Comment by rodrigooler** [comment]
Boa tarde @mozgbrasil agradeço por utilizar a minha lib, irei resolver esse problem e deixar atualizado para você.

**Comment by rodrigooler** [comment]
@mozgbrasil atualizei o repositório e a versão do npm agora está na versão 1.0.1 pode atualizar o pacote e verificar se está funcionando.

**Comment by mozgbrasil** [comment]
Ola

Boa Tarde

Tudo bom meu amigo

Acabo de fazer um teste e está funcionando a validação para o CPF

Voce pretende implementar sua biblioteca com suporte a CNPJ ?

Muito Obrigado e tenha uma ótima semana

**Comment by rodrigooler** [comment]
@mozgbrasil essa atualização está bem simples como estou bastante ocupado acabei não implementando a parte do CNPJ mas irei fazer em breve no mesmo formato de funções do CPF. Se sobrar tempo essa semana irei refatorar essa lib para Babel e incremento a parte do CNPJ. Mas fico muito feliz por estar utilizando minha lib espero que esteja te ajudando.

Att.

**Comment by mozgbrasil** [comment]
Obrigado pela disponibilização da biblioteca

Eu estou fascinado com essa forma de usar javascript 

Como eu sempre mexi com website eu não utilizava essa forma de uso via NPM que achei muito legal para testes

**Comment by rodrigooler** [comment]
@mozgbrasil eu que agradeço, qualquer dúvida estou a disposição, dê star no repositório caso a lib o ajudou no seu desenvolvimento e caso queira acompanhar novas libs/modules pode me seguir também no github.
